######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 17 15:57:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += MainWindow.cpp
